---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: pull-registrydemo-source
- name: current-app-info
#- name: artifactory-repository

outputs:
- name: app-manifest-output

run:
  path: pull-registrydemo-source/ci/tasks/app-manifest-prep
