#!/bin/bash

set -xe
cat ./current-app-info/current-app.txt

sed "s/APPNAME/$(cat ./current-app-info/next-app.txt)-$PWS_APP_SUFFIX/" ./pull-registrydemo-source/manifest.yml > ./app-manifest-output/manifest.yml

cat ./app-manifest-output/manifest.yml

#./pull-registrydemo-source/mvnw clean install

curl -uadmin:AP2eUJGk81RwYFjj6RJdrve2MXY -O "http://10.34.53.16:8081/artifactory/myrepo/registrydemo-0.0.2-SNAPSHOT.jar"

ls -al

pwd

cp ./artifactory-repository/registrydemo-0.0.2-SNAPSHOT.jar ./app-manifest-output/registrydemo-0.0.2-SNAPSHOT.jar