---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: pull-registrydemo-source

outputs:
- name: current-app-info

run:
  path: registrydemo/ci/tasks/current-app-get-info
